
- name: create docker certs directory
  become: yes
  file:
    path: /etc/docker/certs.d/cdd-registry.{{FQDN}}
    state: directory
    mode: 0775

- name: copy registry certs to all servers
  become: yes 
  template:
    src: ~/workspace/registry/tls.crt
    dest: /etc/docker/certs.d/cdd-registry.{{FQDN}}/tls.crt

- name: restart docker service
  become: yes
  shell: |
    service docker restart
