# - name: k8s
#   k8s:
#     name: test-ansible
#     api_version: v1
#     kind: Namespace
#     state: present

- name: Adding user {{ cdd_user }}  
  user: name={{ cdd_user }}
        group={{ cdd_user }}
        shell=/bin/bash
        password=${password}
        groups=sudo,docker
        append=yes
        
- name: add user to sudo group
      shell: usermod -aG sudo {{ cdd_user }}
      args:
        executable: /bin/bash

