# - name: k8s
#   k8s:
#     name: test-ansible
#     api_version: v1
#     kind: Namespace
#     state: present

- name: get hashed password
  shell: |
    python -c 'import crypt; print crypt.crypt("This is my Password", "{{ cdd_user_pass }}")'
  register: result

- name: set hashed password
  set_fact:
    password: "{{ result.stdout | trim }}"

- name: Adding group {{ cdd_user }} 
  group:
    name: "{{ cdd_user }}"
    state: present

- name: Adding user {{ cdd_user }}  
  user: name={{ cdd_user }}
        group={{ cdd_user }}
        shell=/bin/bash
        password={{password}}
        groups=sudo,docker
        append=yes
        
- name: add user to sudo group
  shell: |
    usermod -aG sudo {{ cdd_user }}
  args:
    executable: /bin/bash

