- name: create temp dir
  file:
    path: ~/.kube
    state: directory
    mode: 0775
    recurse: yes
  when:

- name: fetch
  fetch:
    src: ~/.kube/config
    dest: ~/.kube/config
    flat: yes
  when: "inventory_hostname == 'master01'"

- name: copy to other servers
  copy:
    src: ~/.kube/config
    dest: ~/.kube/config
  when: "'master01' not in inventory_hostname"

- name: get kube config
  shell: |
    chown $(id -u):$(id -g) ~/.kube/config
    kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
    echo 'alias k=kubectl' >>~/.bashrc
    echo 'complete -F __start_kubectl k' >>~/.bashrc
  when: "'master01' not in inventory_hostname"
