- name: get kube config
  shell: |
    mkdir -p $HOME/.kube
    scp root@master01:~/.kube/config $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  when: "'master01' not in inventory_hostname"
