- name: create metallb install directory
  file:
    path: ~/workspace/metallb
    state: directory
    mode: 0775

- name: copy metallb values.yaml
  template:
    src: metallb_values.yaml.j2
    dest: ~/workspace/metallb/values.yaml

- name: install metallb
  shell: |
    cd ~/workspace/metallb
    helm repo add metallb https://metallb.github.io/metallb
    helm install metallb metallb/metallb
    helm install metallb metallb/metallb --create-namespace --namespace metallb-system -f values.yaml 

- name: create ingress install directory
  file:
    path: ~/workspace/ingress
    state: directory
    mode: 0775

- name: copy ingress cert config
  template:
    src: ingress.conf.j2
    dest: ~/workspace/ingress/ingress.conf

- name: create ingress cert and key
  shell: |
    cd ~/workspace/ingress
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ingress.key -out ingress.crt -config ingress.conf
    kubectl create secret  tls ingress-tls  -n kube-system  --key="ingress.key" --cert="ingress.crt"

- name: install ingress
  shell: |
    cd ~/workspace/ingress
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo update
    helm install ingress-nginx ingress-nginx/ingress-nginx --create-namespace --namespace ingress-nginx  \
    --set controller.extraArgs.default-ssl-certificate=kube-system/ingress-tls \
    --set controller.extraArgs.annotations-prefix=nginx.ingress.kubernetes.io \
    --set defaultBackend.enabled=true \
    --set controller.replicaCount=2 \
    --set controller.name="" \
    --set controller.extraArgs.enable-ssl-passthrough= \
    --set controller.admissionWebhooks.enabled=false

- name: copy tcp-service yaml
  template:
    src: tcp-services.yaml.j2
    dest: ~/workspace/ingress/tcp-services.yaml

- name: copy udp-service yaml
  template:
    src: udp-services.yaml.j2
    dest: ~/workspace/ingress/udp-services.yaml

- name: configure tcp and udp config map
  shell: |
    cd ~/workspace/ingress
    kubectl apply -f tcp-services.yaml -n ingress-nginx
    kubectl apply -f udp-services.yaml -n ingress-nginx