# - name: set hostname
#   shell: |
#     hostnamectl set-hostname {{inventory_hostname}}.{{FQDN}}

# - name: create config
#   template:
#     src: hosts.j2
#     dest: /etc/hosts

- name: open ports for master nodes
  shell: |
    firewall-cmd --zone=public --permanent --add-port=6443/tcp
    firewall-cmd --zone=public --permanent --add-port=2379-2380/tcp
    firewall-cmd --zone=public --permanent --add-port=10250/tcp
    firewall-cmd --zone=public --permanent --add-port=10257/tcp
    firewall-cmd --zone=public --permanent --add-port=10259/tcp
    firewall-cmd --reload
  when: "'master' in inventory_hostname"

- name: open ports for worker nodes
  shell: |
    firewall-cmd --zone=public --permanent --add-port=10250/tcp
    firewall-cmd --zone=public --permanent --add-port=30000-32767/tcp
    firewall-cmd --reload
  when: "'worker' in inventory_hostname"