# - name: host setup
#   hosts: all
#   any_errors_fatal: true
#   gather_facts: no
#   roles:
#     - host_setup

# - name: pre check
#   hosts: CLUSTER
#   any_errors_fatal: true
#   gather_facts: no
#   roles:
#     - pre_check

# - name: configure keepalived and haproxy
#   hosts: MASTER
#   any_errors_fatal: true
#   gather_facts: no
#   roles:
#     - keepalived_haproxy

- name: pre check
  hosts: CLUSTER
  any_errors_fatal: true
  gather_facts: no
  roles:
    - setup_cluster

# - name: get kube config to  all servers
#   hosts: all
#   any_errors_fatal: true
#   gather_facts: no
#   roles:
#     - kube_config