- name: create sc
  shell: |
    helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    helm repo update
    helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --create-namespace --namespace nfs-external-provisioner --set nfs.server=10.164.227.145 --set nfs.path=/data --set storageClass.name=network-block
    kubectl patch storageclass network-block -n nfs-external-provisioner -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

- name: create registry install directory
  file:
    path: ~/workspace/registry
    state: directory
    mode: 0775

- name: copy registry.conf
  template:
    src: registry.conf.j2
    dest: ~/workspace/registry/registry.conf

- name: create ingress secret and key
  shell: |
    cd ~/workspace/registry
    htpasswd -cBb htpasswd admin ericsson123
    kubectl create secret generic  cr-registry-credentials --from-file=htpasswd=./htpasswd -n kube-system
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -config registry.conf
    kubectl create secret  tls cr-registry-tls  -n kube-system  --key="tls.key" --cert="tls.crt"

- name: install registry
  shell: |
    cd ~/workspace/registry
    helm repo add chart-repo https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-adp-gs-all-helm/
    helm repo update
    helm install eric-lcm-container-registry chart-repo/eric-lcm-container-registry --namespace kube-system \
    --set  global.security.tls.enabled=false \
    --set registry.users.secret=cr-registry-credentials \
    --set ingress.enabled=true \
    --set ingress.useHttpProxy=false \
    --set ingress.hostname="cdd-registry.{{cdd_dns_name}}" \
    --set ingress.tls.enabled=true \
    --set ingress.tls.secretName="cr-registry-tls" \
    --set ingress.ingressClass="nginx" \
    --set persistence.persistentVolumeClaim.size=300Gi
