- name: create registry install directory
  file:
    path: ~/workspace/registry
    state: directory
    mode: 0775

- name: copy registry.conf
  template:
    src: registry.conf.j2
    dest: ~/workspace/registry/registry.conf

- name: create ingress secret and key
  shell: |
    cd ~/workspace/registry
    htpasswd -cBb htpasswd admin ericsson123
    kubectl create secret generic  cr-registry-credentials --from-file=htpasswd=./htpasswd -n kube-system
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -config registry.conf
    kubectl create secret  tls cr-registry-tls  -n kube-system  --key="tls.key" --cert="tls.crt"

- name: install registry
  shell: |
    cd ~/workspace/registry
    helm repo add chart-repo https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-adp-gs-all-helm/
    helm repo update
    helm install eric-lcm-container-registry chart-repo/eric-lcm-container-registry --namespace kube-system \
    --set  global.security.tls.enabled=false \
    --set registry.users.secret=cr-registry-credentials \
    --set ingress.enabled=true \
    --set ingress.useHttpProxy=false \
    --set ingress.hostname="cdd-registry.{{FQDN}}" \
    --set ingress.tls.enabled=true \
    --set ingress.tls.secretName="cr-registry-tls" \
    --set ingress.ingressClass="nginx" \
    --set persistence.persistentVolumeClaim.size=300Gi
