- name: cleanup 1
  shell: |
    kubeadm reset -f
    systemctl stop kubelet
    systemctl stop docker
    rm -rf /var/lib/cni/
    rm -rf /var/lib/kubelet/*
    rm -rf /etc/cni/
    rm -rf /etc/kubernetes/*
    rm -rf /var/lib/etcd/*
    rm -rf ~/.kube

- name: cleanup 2
  ignore_errors: yes
  shell: |
    ifconfig docker0 down
    ip link delete docker0
  
- name: cleanup 2
  ignore_errors: yes
  shell: |
    ifconfig cni0 down
    ip link set cni0 down
    ip link delete cni0

- name: cleanup 3
  ignore_errors: yes
  shell: |
    ifconfig tunl0 down
    ip link set tunl0 down
    ip link delete tunl0

- name: cleanup 3
  ignore_errors: yes
  shell: |
    ifconfig flannel.1 down
    ip link set flannel.1 down
    ip link delete flannel.1

- name: cleanup 4
  ignore_errors: yes
  shell: |
    ip addr flush dev tunl0
    ip addr flush dev flannel.1
    ip addr flush dev cni0
    
- name: cleanup 5
  shell: |
    systemctl start docker





